Repository spidernet-io/spiderdoctor, pull requests merged in 2023-04, with the labels that each got.

#323 support cosign for iamge signature and SBOM
  .github/workflows/call-release-image.yaml
Labels: release/feature

#294 change base image
  docs/develop/roadmap.md
  images/agent/Dockerfile
  images/controller/Dockerfile
Labels: release/feature

#318 Improve DNS benchmark performance
  go.mod
  go.sum
  pkg/loadRequest/dns.go
  pkg/utils/stats/stats.go
  vendor/github.com/montanaflynn/stats/.gitignore
  vendor/github.com/montanaflynn/stats/.travis.yml
  vendor/github.com/montanaflynn/stats/CHANGELOG.md
  vendor/github.com/montanaflynn/stats/DOCUMENTATION.md
  vendor/github.com/montanaflynn/stats/LICENSE
  vendor/github.com/montanaflynn/stats/Makefile
  vendor/github.com/montanaflynn/stats/README.md
  vendor/github.com/montanaflynn/stats/correlation.go
  vendor/github.com/montanaflynn/stats/cumulative_sum.go
  vendor/github.com/montanaflynn/stats/data.go
  vendor/github.com/montanaflynn/stats/deviation.go
  vendor/github.com/montanaflynn/stats/distances.go
  vendor/github.com/montanaflynn/stats/doc.go
  vendor/github.com/montanaflynn/stats/entropy.go
  vendor/github.com/montanaflynn/stats/errors.go
  vendor/github.com/montanaflynn/stats/legacy.go
  vendor/github.com/montanaflynn/stats/load.go
  vendor/github.com/montanaflynn/stats/max.go
  vendor/github.com/montanaflynn/stats/mean.go
  vendor/github.com/montanaflynn/stats/median.go
  vendor/github.com/montanaflynn/stats/min.go
  vendor/github.com/montanaflynn/stats/mode.go
  vendor/github.com/montanaflynn/stats/norm.go
  vendor/github.com/montanaflynn/stats/outlier.go
  vendor/github.com/montanaflynn/stats/percentile.go
  vendor/github.com/montanaflynn/stats/quartile.go
  vendor/github.com/montanaflynn/stats/ranksum.go
  vendor/github.com/montanaflynn/stats/regression.go
  vendor/github.com/montanaflynn/stats/round.go
  vendor/github.com/montanaflynn/stats/sample.go
  vendor/github.com/montanaflynn/stats/sigmoid.go
  vendor/github.com/montanaflynn/stats/softmax.go
  vendor/github.com/montanaflynn/stats/sum.go
  vendor/github.com/montanaflynn/stats/util.go
  vendor/github.com/montanaflynn/stats/variance.go
  vendor/modules.txt
Labels: enhancement, release/feature

#324 implementation of crontab function
  charts/crds/spiderdoctor.spidernet.io_netdnss.yaml
  charts/crds/spiderdoctor.spidernet.io_nethttps.yaml
  go.mod
  go.sum
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/common_types.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/nethttp_types.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/zz_generated.deepcopy.go
  pkg/pluginManager/agentTools.go
  pkg/pluginManager/controllerTools.go
  pkg/pluginManager/nethttp/webhook.go
  pkg/pluginManager/schedule.go
  pkg/pluginManager/tools/tools.go
  pkg/pluginManager/utils.go
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/.travis.yml
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/spec.go
  vendor/modules.txt
Labels: release/feature

#326 add targetPod urlPath
  docs/usage/nethttp.md
  pkg/pluginManager/nethttp/agentExecuteTask.go
Labels: release/feature

#325 Implement DNS benchmark function
  charts/crds/spiderdoctor.spidernet.io_netdnss.yaml
  docs/usage/netdns.md
  pkg/k8ObjManager/manager.go
  pkg/k8ObjManager/service.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/netdns_types.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/zz_generated.deepcopy.go
  pkg/loadRequest/dns.go
  pkg/loadRequest/dns_test.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/netdns/webhook.go
Labels: release/feature

#331 update version to v0.4.0-rc0
  Makefile
  VERSION
  charts/Chart.yaml
Labels: release/none

#334 robot update changelog with tag v0.4.0-rc0 to branch github_pages
  changelogs/changelog_from_v0.3.0_to_v0.4.0-rc0.md
Labels: pr/robot_update

#335 docs: add crd define doc
  docs/usage/netdns.md
  docs/usage/nethttp.md
  docs/usage/performance.md
Labels: documentation, release/none
