Repository spidernet-io/spiderdoctor, pull requests merged in 2023-05, with the labels that each got.

#338 robot update changelog with tag v0.4.0-rc0 to branch github_pages
  changelogs/changelog_from_v0.3.0_to_v0.4.0-rc0.md
Labels: pr/robot_update

#346 optimize HTTP client performance
  charts/templates/configmap.yaml
  charts/values.yaml
  docs/usage/performance.md
  go.mod
  go.sum
  pkg/loadRequest/http.go
  pkg/loadRequest/loadDns/dns.go
  pkg/loadRequest/loadDns/dns_suite_test.go
  pkg/loadRequest/loadDns/dns_test.go
  pkg/loadRequest/loadHttp/http.go
  pkg/loadRequest/loadHttp/http_reporter.go
  pkg/loadRequest/loadHttp/http_requester.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/pluginManager/nethttp/agentExecuteTask.go
  pkg/types/types.go
  vendor/github.com/influxdata/tdigest/.gitignore
  vendor/github.com/influxdata/tdigest/LICENSE
  vendor/github.com/influxdata/tdigest/README.md
  vendor/github.com/influxdata/tdigest/centroid.go
  vendor/github.com/influxdata/tdigest/tdigest.go
  vendor/github.com/mailru/easyjson/.gitignore
  vendor/github.com/mailru/easyjson/.travis.yml
  vendor/github.com/mailru/easyjson/Makefile
  vendor/github.com/mailru/easyjson/README.md
  vendor/github.com/mailru/easyjson/helpers.go
  vendor/github.com/mailru/easyjson/raw.go
  vendor/github.com/mailru/easyjson/unknown_fields.go
  vendor/github.com/tsenart/vegeta/v12/LICENSE
  vendor/github.com/tsenart/vegeta/v12/lib/attack.go
  vendor/github.com/tsenart/vegeta/v12/lib/attack_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/histogram.go
  vendor/github.com/tsenart/vegeta/v12/lib/metrics.go
  vendor/github.com/tsenart/vegeta/v12/lib/pacer.go
  vendor/github.com/tsenart/vegeta/v12/lib/reporters.go
  vendor/github.com/tsenart/vegeta/v12/lib/results.go
  vendor/github.com/tsenart/vegeta/v12/lib/results_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/lib/results_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/target.schema.json
  vendor/github.com/tsenart/vegeta/v12/lib/targets.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets_easyjson.go
  vendor/github.com/tsenart/vegeta/v12/lib/targets_fuzz.go
  vendor/github.com/tsenart/vegeta/v12/lib/util_fuzz.go
  vendor/modules.txt
Labels: enhancement, release/feature

#357 optimize DNS client performance
  charts/templates/configmap.yaml
  charts/values.yaml
  go.mod
  go.sum
  pkg/loadRequest/loadDns/dns.go
  pkg/loadRequest/loadDns/dns_reporter.go
  pkg/loadRequest/loadDns/dns_requester.go
  pkg/loadRequest/loadDns/dns_suite_test.go
  pkg/loadRequest/loadDns/dns_test.go
  pkg/pluginManager/netdns/agentExecuteTask.go
  pkg/types/types.go
  vendor/github.com/andres-erbsen/clock/.travis.yml
  vendor/github.com/andres-erbsen/clock/LICENSE
  vendor/github.com/andres-erbsen/clock/README.md
  vendor/github.com/andres-erbsen/clock/clock.go
  vendor/go.uber.org/ratelimit/.gitignore
  vendor/go.uber.org/ratelimit/CHANGELOG.md
  vendor/go.uber.org/ratelimit/LICENSE
  vendor/go.uber.org/ratelimit/Makefile
  vendor/go.uber.org/ratelimit/README.md
  vendor/go.uber.org/ratelimit/limiter_atomic.go
  vendor/go.uber.org/ratelimit/limiter_mutexbased.go
  vendor/go.uber.org/ratelimit/ratelimit.go
  vendor/modules.txt
Labels: enhancement, release/feature

#359 split http crd
  charts/crds/spiderdoctor.spidernet.io_httpapphealthys.yaml
  charts/crds/spiderdoctor.spidernet.io_nethttps.yaml
  charts/crds/spiderdoctor.spidernet.io_netreachhealthys.yaml
  charts/templates/role.yaml
  charts/templates/tls.yaml
  docs/usage/httpapphealthy.md
  docs/usage/nethttp.md
  docs/usage/netreachhealthy.md
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/common_types.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/httpapphealthy_types.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/nethttp_types.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/netreachhealthy_types.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/rbac.go
  pkg/k8s/apis/spiderdoctor.spidernet.io/v1beta1/zz_generated.deepcopy.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/fake/fake_httpapphealthy.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/fake/fake_nethttp.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/fake/fake_netreachhealthy.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/fake/fake_spiderdoctor.spidernet.io_client.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/generated_expansion.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/httpapphealthy.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/nethttp.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/netreachhealthy.go
  pkg/k8s/client/clientset/versioned/typed/spiderdoctor.spidernet.io/v1beta1/spiderdoctor.spidernet.io_client.go
  pkg/k8s/client/informers/externalversions/generic.go
  pkg/k8s/client/informers/externalversions/spiderdoctor.spidernet.io/v1beta1/httpapphealthy.go
  pkg/k8s/client/informers/externalversions/spiderdoctor.spidernet.io/v1beta1/interface.go
  pkg/k8s/client/informers/externalversions/spiderdoctor.spidernet.io/v1beta1/netreachhealthy.go
  pkg/k8s/client/listers/spiderdoctor.spidernet.io/v1beta1/expansion_generated.go
  pkg/k8s/client/listers/spiderdoctor.spidernet.io/v1beta1/httpapphealthy.go
  pkg/k8s/client/listers/spiderdoctor.spidernet.io/v1beta1/nethttp.go
  pkg/k8s/client/listers/spiderdoctor.spidernet.io/v1beta1/netreachhealthy.go
  pkg/pluginManager/agentReconciler.go
  pkg/pluginManager/agentTools.go
  pkg/pluginManager/controllerReconciler.go
  pkg/pluginManager/httpapphealthy/agentExecuteTask.go
  pkg/pluginManager/httpapphealthy/plugin.go
  pkg/pluginManager/httpapphealthy/webhook.go
  pkg/pluginManager/manager.go
  pkg/pluginManager/netreachhealthy/agentExecuteTask.go
  pkg/pluginManager/netreachhealthy/plugin.go
  pkg/pluginManager/netreachhealthy/webhook.go
Labels: release/feature

#376 update version to v0.4.0-rc1
  VERSION
  charts/Chart.yaml
Labels: release/none
